### ISSUE TITLE
`npm install` via npm@6 reports 4276 vulnerabilities

### ISSUE THREAD

**Issue by RA80533** [layer0-platform/rum#15]
```console
$ npx -p npm@6 npm install
npm WARN @layer0/rum@2.1.2 No repository field.

audited 1355 packages in 5.53s

94 packages are looking for funding
  run `npm fund` for details

found 4276 vulnerabilities (177 moderate, 4099 high)
  run `npm audit fix` to fix them, or `npm audit` for details
```

It appears that most of the development for this project happens using npm 6.x so at least some of these should have been appearing.

Related #14

**Comment by petrvecera** [comment]
All the "dependencies" of the project has been updated to the latest versions.
The vulnerabilities might be coming from the devDependencies. That should not be a problem. 

Thanks for reporting this anyway 👍
